### ISSUE TITLE
Namespace change not applied to functions

### ISSUE THREAD

**Issue by DeepDiver1975** [TypistTech/imposter-plugin#42]
What would need to be done to address this? THX

Example: https://drone.owncloud.com/owncloud/files_primary_s3/589/42
```
Error: Call to undefined function Aws\manifest() in /drone/server/apps/files_primary_s3/vendor/aws/aws-sdk-php/src/Api/ApiProvider.php:97
Stack trace:
#0 /drone/server/apps/files_primary_s3/vendor/aws/aws-sdk-php/src/ClientResolver.php(260): OCA\Files_Primary_S3\Vendor\Aws\Api\ApiProvider::defaultProvider(Array)
#1 /drone/server/apps/files_primary_s3/vendor/aws/aws-sdk-php/src/AwsClient.php(161): OCA\Files_Primary_S3\Vendor\Aws\ClientResolver->resolve(Array, Object(OCA\Files_Primary_S3\Vendor\Aws\HandlerList))
#2 /drone/server/apps/files_primary_s3/vendor/aws/aws-sdk-php/src/S3/S3Client.php(263): OCA\Files_Primary_S3\Vendor\Aws\AwsClient->__construct(Array)
#3 /drone/server/apps/files_primary_s3/lib/command/createbucket.php(109): OCA\Files_Primary_S3\Vendor\Aws\S3\S3Client->__construct(Array)
#4 /drone/server/apps/files_primary_s3/lib/command/createbucket.php(72): OCA\Files_Primary_S3\Command\createBucket->getClient()
#5 /drone/server/lib/composer/symfony/console/Command/Command.php(255): OCA\Files_Primary_S3\Command\createBucket->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /drone/server/lib/composer/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /drone/server/lib/composer/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files_Primary_S3\Command\createBucket), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /drone/server/lib/composer/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /drone/server/lib/private/Console/Application.php(161): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /drone/server/console.php(106): OC\Console\Application->run()
#11 /drone/server/occ(11): require_once('/drone/server/c...')
#12 {main}

**Comment by DeepDiver1975** [comment]
moved to https://github.com/TypistTech/imposter/issues/75
